[[includes]]
url = "https://raw.githubusercontent.com/arceos-hypervisor/axvisor-guest-registry/refs/heads/main/v0.0.20.toml"

[[includes]]
url = "https://raw.githubusercontent.com/arceos-hypervisor/axvisor-guest-registry/refs/heads/main/v0.0.22.toml"
